version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - errorlint
    - misspell
    - nolintlint
  exclusions:
    generated: strict

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
