ARG GO_IMAGE=golang:1.26.6-alpine
ARG RUNTIME_IMAGE=alpine:3.22

FROM ${GO_IMAGE} AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build \
    -mod=readonly \
    -trimpath \
    -buildvcs=false \
    -ldflags="-s -w" \
    -o /out/railyard-worker \
    ./cmd/railyard-worker

FROM ${RUNTIME_IMAGE}
RUN apk add --no-cache ca-certificates \
    && addgroup -S -g 10001 railyard \
    && adduser -S -D -H -u 10001 -G railyard railyard

COPY --from=build --chown=railyard:railyard \
    /out/railyard-worker \
    /usr/local/bin/railyard-worker

USER railyard:railyard
WORKDIR /tmp

ENTRYPOINT ["/usr/local/bin/railyard-worker"]
